public enum ItemType
{
    BUCKET = 0,
    SALTWATER = 1,
    FRESH_APPLE = 2,
    RAW_RUBY = 3,
    DISORDERED_SPIRIT = 4,
    SPARKLING_APPLE = 5,
    MINOR_SPIRIT = 6,
    PURE_WATER = 7,
    SALT = 8,
    SPARKLING_RUBY = 9,
    GEMSTONE_DUST = 10,
    POTION_CALM = 11,
    POTION_HEAL = 12,
    POTION_MANA = 13
}